#!/bin/tcsh
#BSUB -q 2nw
#BSUB -J Zssm1000
#BSUB -o /afs/cern.ch/user/t/tucker/scratch0/Zp2mu_GEN_SIM_DIGI_RECO_%J.lis

# to do:
# change job name
# change SAMPLE
# check OUTDIR
# check RNG seed
# change PYTHIA settings
# enable simulation or no

echo  -------------------------------------------
echo   $0 batch job started at `date`
echo   GEN_SIM_DIGI_RECO for CMSSW 2_0_6
echo  -------------------------------------------

setenv CMSSW_VERS CMSSW_2_0_6
setenv WRITE_TO_CASTOR 1
setenv NEVENTS 1000
setenv WRITE_CFG_ONLY 0 # set to write out the cfg file, which can then be used by crab

setenv SRCDIR /afs/cern.ch/user/t/tucker/private/${CMSSW_VERS}
setenv OUTDIR /castor/cern.ch/user/t/tucker/${CMSSW_VERS}
if (! $?WORKDIR) then
    setenv WORKDIR /tmp/tucker
endif

 setenv MASS 1000 ; setenv MCUT  400
#setenv MASS 1500 ; setenv MCUT  600
#setenv MASS 2000 ; setenv MCUT 1000
#setenv MASS 3000 ; setenv MCUT 1500

 setenv MODEL Zssm
#setenv MODEL Zpsi
#setenv MODEL dy ; setenv MCUT 400

if (${MODEL} == "dy") then
  setenv SAMPLE dy_above${MCUT}
  setenv MIXING 4 # only Z0/gamma interference included
else
  setenv SAMPLE ${MODEL}${MASS}_fm
  setenv MIXING 7 # complete Zprime/Z/gamma interference
endif

if (${MODEL} == "Zpsi") then 
  setenv ZPCOUPLINGS '\
        # Couplings: first generation\
	"PARU(121)=  0.        ! vd",\
	"PARU(122)= -0.506809  ! ad",\
	"PARU(123)=  0.        ! vu",\
	"PARU(124)= -0.506809  ! au",\
	"PARU(125)=  0.        ! ve",\
	"PARU(126)= -0.506809  ! ae",\
	"PARU(127)= -0.253405  ! vnu",\
	"PARU(128)= -0.253405  ! anu",\
        # Couplings: second generation\
	"PARJ(180)=  0.        ! vd",\
	"PARJ(181)= -0.506809  ! ad",\
	"PARJ(182)=  0.        ! vu",\
	"PARJ(183)= -0.506809  ! au",\
	"PARJ(184)=  0.        ! ve",\
	"PARJ(185)= -0.506809  ! ae",\
	"PARJ(186)= -0.253405  ! vnu",\
	"PARJ(187)= -0.253405  ! anu",\
        # Couplings: third generation\
	"PARJ(188)=  0.        ! vd",\
	"PARJ(189)= -0.506809  ! ad",\
	"PARJ(190)=  0.        ! vu",\
	"PARJ(191)= -0.506809  ! au",\
	"PARJ(192)=  0.        ! ve",\
	"PARJ(193)= -0.506809  ! ae",\
	"PARJ(194)= -0.253405  ! vnu",\
	"PARJ(195)= -0.253405  ! anu",'
else
  setenv ZPCOUPLINGS ""
endif

############################################################################
# Below here is the domain of the expert.
############################################################################

echo '**************' $SAMPLE '**************'

if (! $WRITE_CFG_ONLY) then
    rfmkdir -p ${OUTDIR}
  
    cd ${SRCDIR}
    eval `scramv1 runtime -csh`
    cd ${WORKDIR}
endif

echo '************** GEN-SIM-DIGI-L1-RAW-RECO **************'
cat >! GEN_SIM_DIGI_RECO.cfg <<EOF
# Configuration file for production of resonance --> mu+ mu-.
# Zprime2mu part is translation to CMSSW language of control cards used
# in PYTHIA and CMKIN since 2002; the rest is standard.
process Rec = {

  untracked PSet maxEvents = {untracked int32 input = ${NEVENTS}}

  include "Configuration/StandardSequences/data/Services.cff"
  include "Configuration/StandardSequences/data/Geometry.cff"
  include "Configuration/StandardSequences/data/MagneticField.cff"

  #include "Configuration/StandardSequences/data/FakeConditions.cff" 
  include "Configuration/StandardSequences/data/FrontierConditions_GlobalTag.cff"
  # Currently available TAGNAMEs are: STARTUP, 1PB, 10PB, IDEAL
  replace GlobalTag.globaltag = "IDEAL::All"

  include "FWCore/MessageService/data/MessageLogger.cfi"

  # Initialize random number seeds
  include "Configuration/StandardSequences/data/SimulationRandomNumberGeneratorSeeds.cff"
  #replace RandomNumberGeneratorService.sourceSeed = 12191982

  untracked PSet options = {
    include "FWCore/Framework/test/cmsExceptionsFatalOption.cff"
    untracked bool wantSummary = true
    untracked bool makeTriggerResults = true
  }

  # Event generation
  include "Configuration/Generator/data/PythiaUESettings.cfi"
  source = PythiaSource { 
    # to printout pythia event record (call pylist)
    untracked int32 pythiaPylistVerbosity = 0
    # to printout HepMC::GenEvent record (HepMC::GenEvent::print())
    untracked bool pythiaHepMCVerbosity = false
    untracked int32 maxEventsToPrint = 0
    
    PSet PythiaParameters = {
      # This is a vector of ParameterSet names to be read, in this order
      vstring parameterSets = {
	"pythiaUESettings",
        # Choose just one of the following!
	"Zprime2mu"
#	"RS1Graviton"
      }
      
      using pythiaUESettingsBlock

      vstring Zprime2mu = {
	"MSEL = 21            ! generate Zprime according to ISUB=141",
        # Treatment of Z'/Z0/gamma interference
        #"MSTP(44) = 2        ! only Z0 included",
        #"MSTP(44) = 3        ! only Zprime included",
        #"MSTP(44) = 4        ! only Z0/gamma interference included",
        #"MSTP(44) = 7        ! complete Zprime/Z/gamma interference",
        "MSTP(44) = ${MIXING}",	
        # Z' mass
	"PMAS(32,1) = ${MASS}.0  ! PMAS(KC,1) is mass of particle KC",
        # Range of allowed M values
	"CKIN(1) = ${MCUT}.0",
	#"CKIN(2) =  500.     ! upper mass limit",
	${ZPCOUPLINGS}
        # Decay modes
	"MDME(289,1) = 0      ! d + dbar",
	"MDME(290,1) = 0      ! u + ubar",
	"MDME(291,1) = 0      ! s + sbar",
	"MDME(292,1) = 0      ! c + cbar",
	"MDME(293,1) = 0      ! b + bbar",
	"MDME(294,1) = 0      ! t + tbar",
	"MDME(295,1) =-1      ! 4th generation q + qbar",
	"MDME(296,1) =-1      ! 4th generation q + qbar",
	"MDME(297,1) = 0      ! e-     + e+",
	"MDME(298,1) = 0      ! nu_e   + nu_ebar",
	"MDME(299,1) = 1      ! mu-    + mu+",
	"MDME(300,1) = 0      ! nu_mu  + nu_mubar",
	"MDME(301,1) = 0      ! tau-   + tau+",
	"MDME(302,1) = 0      ! nu_tau + nu_taubar",
	"MDME(303,1) =-1      ! 4th generation l- + l+",
	"MDME(304,1) =-1      ! 4th generation nu + nubar",
	"MDME(305,1) =-1      ! W+ + W-",
	"MDME(306,1) =-1      ! H+ + H-",
	"MDME(307,1) =-1      ! Z0 + gamma",
	"MDME(308,1) =-1      ! Z0 + h0",
	"MDME(309,1) =-1      ! h0 + A0",
	"MDME(310,1) =-1      ! H0 + A0"
      }

      vstring RS1Graviton = {
        # Randall-Sundrum lowest excited graviton state.
        "MSEL = 0             ! select between full user control (0) and some preprogrammed alternative",
        "MSUB(391) = 1        ! q qbar -> G*",
        "MSUB(392) = 1        ! g g -> G*",
        # Dimensionless constant defining graviton couplings and widths.
        # PARP(50) is defined as sqrt(2)*x_1*k/M_{Pl}, where x_1 is the
        # first root of J_1 Bessel function and is equal to 3.8317.
        # The default is 0.054 corresponding to c=k/M_{Pl} of 0.01.
        "PARP(50) = 0.54      ! 0.54 == c=0.1",
        # Graviton mass.  KC code for R-S G* is 347, but may change.  Check it by
        # printing KC=PYCOMP(5000039) value.
        "PMAS(347,1) = 5000", #${MASS}.0 ! PMAS(KC,1) is mass of particle KC",
        # Range of allowed M values
	"CKIN(1) = ${MCUT}.0",
        # Used in official production, but I (SV) do not know the reason for this.
        #"CKIN(3) = 20.        ! minimum pt hat for hard interactions",
        # Decay modes
        "MDME(4158,1) = 0     ! d + dbar",
        "MDME(4159,1) = 0     ! u + ubar",
        "MDME(4160,1) = 0     ! s + sbar",
        "MDME(4161,1) = 0     ! c + cbar",
        "MDME(4162,1) = 0     ! b + bbar",
        "MDME(4163,1) = 0     ! t + tbar",
        "MDME(4164,1) =-1     ! bprime + bprimebar",
        "MDME(4165,1) =-1     ! tprime + tprimebar",
        "MDME(4166,1) = 0     ! e+     + e-",
        "MDME(4167,1) = 0     ! nu_e   + nu_ebar",
        "MDME(4168,1) = 1     ! mu-    + mu+",
        "MDME(4169,1) = 0     ! nu_mu  + nu_mubar",
        "MDME(4170,1) = 0     ! tau-   + tau+",
        "MDME(4171,1) = 0     ! nu_tau + nu_taubar",
        "MDME(4172,1) =-1     ! tauprime- + tauprime+",
        "MDME(4173,1) =-1     ! nuprime_tau + nuprime_taubar",
        "MDME(4174,1) = 0     ! g + g",
        "MDME(4175,1) = 0     ! gamma + gamma",
        "MDME(4176,1) = 0     ! Z + Z",
        "MDME(4177,1) = 0     ! W + W"
      }
    }
  }

#  source = FlatRandomEGunSource {
#    untracked PSet PGunParameters = {
#      untracked vint32 PartID = { 13 }
#      untracked double MinEta = 0.9
#      untracked double MaxEta = 2.4
#      untracked double MinPhi = -3.14159265358979323846 # in radians
#      untracked double MaxPhi =  3.14159265358979323846
#      untracked double MinE  = 3000.
#      untracked double MaxE  = 3000.
#    }
#    untracked bool AddAntiParticle = true # back-to-back particles
#    untracked int32 Verbosity = 0
#  }

  include "Configuration/StandardSequences/data/Generator.cff"
  include "Configuration/StandardSequences/data/Simulation.cff"

  #include "Configuration/StandardSequences/data/VtxSmearedGauss.cff"
  #include "Configuration/StandardSequences/data/VtxSmearedFlat.cff"
  #include "Configuration/StandardSequences/data/VtxSmearedBeamProfile.cff"
  #include "Configuration/StandardSequences/data/VtxSmearedBetafuncNominalCollision.cff"
  include "Configuration/StandardSequences/data/VtxSmearedBetafuncEarlyCollision.cff"

  include "Configuration/StandardSequences/data/MixingNoPileUp.cff"
  #include "Configuration/StandardSequences/data/MixingLowLumiPileUp.cff"
  #include "Configuration/StandardSequences/data/MixingHighLumiPileUp.cff"

  include "Configuration/StandardSequences/data/L1Emulator.cff" 
  include "Configuration/StandardSequences/data/DigiToRaw.cff"

  ## use the following for the unprescaled L1 2E30 menu:
  #include "Configuration/StandardSequences/data/L1TriggerDefaultMenu.cff"
  #include "HLTrigger/Configuration/data/HLT_2E30.cff"
  #include "HLTrigger/Configuration/data/common/HLTPrescaleReset.cff"

  include "Configuration/StandardSequences/data/Reconstruction.cff"
  include "RecoMuon/GlobalMuonProducer/data/tevMuons.cfi"
  
  # Add extra muon reconstructors to FEVTSIM
  block ExtraMuonReco = {
    untracked vstring outputCommands = {
      "keep *_tevMuons_*_*"
    }
  }

  include "Configuration/EventContent/data/EventContent.cff"
  replace FEVTSIMEventContent.outputCommands += ExtraMuonReco.outputCommands

  module out = PoolOutputModule {
    untracked string fileName = "reco.root"
    using FEVTSIMEventContent
    untracked PSet dataset = {
	untracked string dataTier = "GEN-SIM-DIGI-RAW-L1-RECO"
    }
  }

  path p0 = {pgen}
  path p1 = {psim}
  path p2 = {pdigi}
  path p3 = {L1Emulator}
  path p4 = {DigiToRaw}
  path p5 = {reconstruction, tevMuons}
  
  endpath outpath = { out }
  
  schedule = {p0,p1,p2,p3,p4,p5,outpath}
}
EOF

if (! ${WRITE_CFG_ONLY}) then 
    cmsRun Zp2mu_GEN_SIM_DIGI_RECO.cfg
    if ($? != 0) then
      echo ' CMSSW (Zp2mu_GEN_SIM_DIGI_RECO) exited with error code'
      exit 1
    endif
    ls

    if (${WRITE_TO_CASTOR}) then
      rfcp reco.root ${OUTDIR}/${SAMPLE}_GEN_SIM_DIGI_RECO.root
      rfdir ${OUTDIR}
    endif
endif

echo
echo  -------------------------------------------
echo   $0 finished at `date`
echo  -------------------------------------------
